version: "3"
services:
  web:
    build: .
    image: kewen123/cs3219-otot-b
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - API_PORT=8081
      - MONGO_URI=mongodb://mongo:27017
